<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GLEM.App</RootNamespace>
    <ApplicationIcon>Assets\GLEM.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\GLEM.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="ScottPlot.WPF" Version="5.0.39" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GLEM.Core\GLEM.Core.csproj" />
  </ItemGroup>

</Project>
