# GLEM coverage gate script (test plan section 5.2 quality gate)
# Rule: GLEM.Core line coverage >= threshold (default 80%). Passes when no GLEM.Core lines are measured (M0).
# Input: Cobertura XML generated by coverlet / XPlat Code Coverage, or legacy coveragexml format.
param(
    [Parameter(Mandatory = $true)]
    [string]$CoverageXmlPath,

    [double]$ThresholdPercent = 80.0
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $CoverageXmlPath)) {
    Write-Error "coverage file not found: $CoverageXmlPath"
    exit 1
}

[xml]$doc = Get-Content -LiteralPath $CoverageXmlPath -Encoding UTF8

$totalLines = 0
$coveredLines = 0

if ($null -ne $doc.coverage.packages) {
    # Cobertura format (default output of coverlet / XPlat Code Coverage)
    foreach ($pkg in @($doc.coverage.packages.package)) {
        if (-not ($pkg.name -like 'GLEM.Core*')) {
            continue
        }

        foreach ($cls in @($pkg.classes.class)) {
            foreach ($line in @($cls.lines.line)) {
                $totalLines++
                if ([int]$line.hits -gt 0) {
                    $coveredLines++
                }
            }
        }
    }
}
else {
    # coveragexml format (fallback)
    foreach ($source in @($doc.coverage.sources.source)) {
        foreach ($file in @($source.file)) {
            if (-not ($file.name -like '*GLEM.Core*')) {
                continue
            }

            foreach ($cls in @($file.class)) {
                $lines = [int]$cls.'line-count'
                $rate = [double]$cls.'line-rate'
                $totalLines += $lines
                $coveredLines += [math]::Round($lines * $rate)
            }
        }
    }
}

if ($totalLines -eq 0) {
    Write-Host "No GLEM.Core lines found in coverage report; gate passes."
    exit 0
}

$percent = 100.0 * $coveredLines / $totalLines
Write-Host ("GLEM.Core line coverage: {0:N2}% ({1}/{2})" -f $percent, $coveredLines, $totalLines)

if ($percent -lt $ThresholdPercent) {
    Write-Host "FAIL: below threshold ${ThresholdPercent}%"
    exit 1
}

Write-Host "PASS: at or above threshold ${ThresholdPercent}%"
exit 0
