//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLEM.App.Properties {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("MissingLocalizationsLabel", "CA2000:Dispose objects before losing scope")]
        internal AppResources() {
        }

        /// <summary>
        ///   Looks up a localized string similar to The language setting has been saved. Restart GLEM to apply it..
        /// </summary>
        public static string Dialog_RestartRequiredMessage {
            get {
                return ResourceManager.GetString("Dialog_RestartRequiredMessage", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GLEM - Language.
        /// </summary>
        public static string Dialog_RestartRequiredTitle {
            get {
                return ResourceManager.GetString("Dialog_RestartRequiredTitle", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        public static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _English.
        /// </summary>
        public static string Menu_LanguageEnglish {
            get {
                return ResourceManager.GetString("Menu_LanguageEnglish", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Japanese.
        /// </summary>
        public static string Menu_LanguageJapanese {
            get {
                return ResourceManager.GetString("Menu_LanguageJapanese", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _System default.
        /// </summary>
        public static string Menu_LanguageSystem {
            get {
                return ResourceManager.GetString("Menu_LanguageSystem", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bishop simplified.
        /// </summary>
        public static string SlopeMethod_BishopSimplified {
            get {
                return ResourceManager.GetString("SlopeMethod_BishopSimplified", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fellenius.
        /// </summary>
        public static string SlopeMethod_Fellenius {
            get {
                return ResourceManager.GetString("SlopeMethod_Fellenius", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Janbu generalized.
        /// </summary>
        public static string SlopeMethod_JanbuGeneralized {
            get {
                return ResourceManager.GetString("SlopeMethod_JanbuGeneralized", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Validation: failed.
        /// </summary>
        public static string Validation_Failed {
            get {
                return ResourceManager.GetString("Validation_Failed", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Validation: passed.
        /// </summary>
        public static string Validation_Passed {
            get {
                return ResourceManager.GetString("Validation_Passed", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new global::System.Resources.ResourceManager("GLEM.App.Properties.AppResources", typeof(AppResources).Assembly);
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread&apos;s CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
